apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: operatorimagesupdate-pipeline-service-pipeline-service-uibb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operatorimagesupdate-pipeline-service-pipeline-service-uibb
    app.kubernetes.io/part-of: plnsvc
  name: operatorimagesupdate-pipeline-service-pipeline-service-uibb
  namespace: rarnaud-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: operatorimagesupdate-pipeline-service-pipeline-service-uibb
status:
  loadBalancer: {}
