apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ciimagesstatic-checks-pipeline-service-obmz
  namespace: rarnaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d6d1945f76be561aa18e55733251ea727b439753846025724d56e7d4770a1e8e
        name: container-image
        resources: {}
status: {}
