apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-lp4u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ciimagesstatic-checks-pipeline-service-lp4u
    app.kubernetes.io/part-of: plnsvc
  name: ciimagesstatic-checks-pipeline-service-lp4u
  namespace: rarnaud-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ciimagesstatic-checks-pipeline-service-lp4u
    weight: 100
status: {}
