apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-lp4u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ciimagesstatic-checks-pipeline-service-lp4u
    app.kubernetes.io/part-of: plnsvc
  name: ciimagesstatic-checks-pipeline-service-lp4u
  namespace: rarnaud-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-lp4u
status:
  loadBalancer: {}
