apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-obmz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ciimagesstatic-checks-pipeline-service-obmz
    app.kubernetes.io/part-of: plnsvc
  name: ciimagesstatic-checks-pipeline-service-obmz
  namespace: rarnaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-obmz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ciimagesstatic-checks-pipeline-service-obmz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d6d1945f76be561aa18e55733251ea727b439753846025724d56e7d4770a1e8e
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
